// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRZwDLhuo_7e75OE7nWyngUJYde1EE8Uo',
    appId: '1:648795845826:web:153b64bd58f56649a9b75b',
    messagingSenderId: '648795845826',
    projectId: 'porto-60356',
    authDomain: 'porto-60356.firebaseapp.com',
    storageBucket: 'porto-60356.appspot.com',
    measurementId: 'G-220FG8WSNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gAaIrH2omo4aTICfn4buqRPPWkeH_MU',
    appId: '1:648795845826:android:c44f079a25af37c6a9b75b',
    messagingSenderId: '648795845826',
    projectId: 'porto-60356',
    storageBucket: 'porto-60356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiy7Ti_DEeTb2ogiwQyBBQgBjLwuCQ9Dc',
    appId: '1:648795845826:ios:c88a3734fd43d446a9b75b',
    messagingSenderId: '648795845826',
    projectId: 'porto-60356',
    storageBucket: 'porto-60356.appspot.com',
    iosClientId: '648795845826-hjhamlh2ehqp4lsgbiqh5pknn8teq090.apps.googleusercontent.com',
    iosBundleId: 'com.example.portoWeb',
  );
}
